### ISSUE TITLE
CRTM_tutorial unable to compile with CRTM-2.2.3

### ISSUE THREAD

**Issue by raj879423** [StegmannJCSDA/CRTM_tutorial#8]
I have compiled crtm-2.2.3 with GCC-6.3.0 successfully. Now I am unable to compile CRTM_tutorial with crtm-2.2.3.

As per Github forum it is mentioned we can be compiled with 2.1.3 to 2.3.0.
 
Kindly suggest me something on this on priority.  

Basically, we have 3 files in CRTM_tutorial -:

1st - K-Matrix_SVD              -  runs successfully 
2nd - K-Matrix_test             - error 
3rd - NakajimaKing             - error

============================================

This is the makefile of "K-Matrix_test"
```
$ cat makefile
all:
        gfortran -c -I/home/raj/codes/gcc/crtm_v2.2.3/include KMatrix_test.f90
        gfortran /home/raj/codes/gcc/crtm_v2.2.3/lib/libcrtm.a -o K.x KMatrix_test.o

clean:
        @rm *.o *.mod
```
-------------------------------------------------------------------------------------------------------
Now here is the error after running make.
```
make
gfortran -c -I/home/raj/codes/gcc/crtm_v2.2.3/include KMatrix_test.f90
gfortran /home/raj/codes/gcc/crtm_v2.2.3/lib/libcrtm.a -o K.x KMatrix_test.o
KMatrix_test.o: In function `MAIN__':
KMatrix_test.f90:(.text+0x19fe): undefined reference to `__crtm_module_MOD_crtm_version'
KMatrix_test.f90:(.text+0x1ab7): undefined reference to `__message_handler_MOD_program_message'
KMatrix_test.f90:(.text+0x1e0e): undefined reference to `__crtm_lifecycle_MOD_crtm_init'
KMatrix_test.f90:(.text+0x1ecf): undefined reference to `__message_handler_MOD_display_message'
KMatrix_test.f90:(.text+0x1f12): undefined reference to `__crtm_channelinfo_define_MOD_crtm_channelinfo_n_channels'
KMatrix_test.f90:(.text+0x4812): undefined reference to `__message_handler_MOD_display_message'
KMatrix_test.f90:(.text+0x4884): undefined reference to `__crtm_atmosphere_define_MOD_crtm_atmosphere_create'
KMatrix_test.f90:(.text+0x48bb): undefined reference to `__crtm_atmosphere_define_MOD_crtm_atmosphere_associated'
KMatrix_test.f90:(.text+0x49a5): undefined reference to `__message_handler_MOD_display_message'
KMatrix_test.f90:(.text+0x4a77): undefined reference to `__crtm_atmosphere_define_MOD_crtm_atmosphere_create'
KMatrix_test.f90:(.text+0x4b16): undefined reference to `__crtm_atmosphere_define_MOD_crtm_atmosphere_associated'
KMatrix_test.f90:(.text+0x4c0f): undefined reference to `__message_handler_MOD_display_message'
KMatrix_test.f90:(.text+0x4cb1): undefined reference to `__crtm_geometry_define_MOD_crtm_geometry_setvalue'
KMatrix_test.f90:(.text+0x4d41): undefined reference to `__crtm_atmosphere_define_MOD_crtm_atmosphere_zero'
KMatrix_test.f90:(.text+0x4dcb): undefined reference to `__crtm_surface_define_MOD_crtm_surface_zero'
KMatrix_test.f90:(.text+0x50df): undefined reference to `__crtm_k_matrix_module_MOD_crtm_k_matrix'
KMatrix_test.f90:(.text+0x51a1): undefined reference to `__message_handler_MOD_display_message'
KMatrix_test.f90:(.text+0x5756): undefined reference to `__crtm_lifecycle_MOD_crtm_destroy'
KMatrix_test.f90:(.text+0x580a): undefined reference to `__message_handler_MOD_display_message'
KMatrix_test.f90:(.text+0x58a3): undefined reference to `__crtm_atmosphere_define_MOD_crtm_atmosphere_destroy'
KMatrix_test.f90:(.text+0x58da): undefined reference to `__crtm_atmosphere_define_MOD_crtm_atmosphere_destroy'
collect2: error: ld returned 1 exit status
makefile:2: recipe for target 'all' failed
make: *** [all] Error 1


EOF
```

Please can anyone suggest me or help me to solve this issue.
I am unable to solve for very long time.

**Comment by StegmannJCSDA** [comment]
Hello @raj879423, thank you for your interest.

I have not tested the CRTM with version 2.2.3, but your error message usually means that the compiler is not able to find the `*.mod` module files of the CRTM.

Can you check if e.g. `crtm_atmosphere_define.mod` is located in your `/home/raj/codes/gcc/crtm_v2.2.3/include` folder?

**Comment by raj879423** [comment]
> Hello @raj879423, thank you for your interest.
> 
> I have not tested the CRTM with version 2.2.3, but your error message usually means that the compiler is not able to find the `*.mod` module files of the CRTM.
> 
> Can you check if e.g. `crtm_atmosphere_define.mod` is located in your `/home/raj/codes/gcc/crtm_v2.2.3/include` folder?




Hello StegmannJCSDA,

Yes I have this file on my include location.
 ```
[raj@utility04 include]$ pwd 
/home/raj/codes/gcc/crtm_v2.2.3/include
[raj@utility04 include]$ ls crtm_atmosphere_define.mod
crtm_atmosphere_define.mod
```

Kindly suggest me what should I mention in makefile of each -: K-Matrix_SVD , K-Matrix_test , NakajimaKing .
Actually, I am unable to compile with gcc or with intel, none of this are support for CRTM_Tutorial. 
I have compiled CRTM REL_2.2.3 with gcc and another end, we have compiled CRTM REL_2.3.0 with Intel in both the case i am getting error for CRTM_Tutorial.

I would request you please help me to solve this issue at least give me some idea or document to compile crtm_tutorial with gcc or with intel.



Thanks & Regards 
Raj

**Comment by raj879423** [comment]
Hello StegmannJCSDA,

Yes I have this file on my include location.
```
[raj@utility04 include]$ pwd
/home/raj/codes/gcc/crtm_v2.2.3/include
[raj@utility04 include]$ ls crtm_atmosphere_define.mod
crtm_atmosphere_define.mod
```
Kindly suggest me what should I mention in makefile of each -: K-Matrix_SVD , K-Matrix_test , NakajimaKing .
Actually, I am unable to compile with gcc or with intel, none of this are support for CRTM_Tutorial.
I have compiled CRTM REL_2.2.3 with gcc and another end, we have compiled CRTM REL_2.3.0 with Intel in both the case i am getting error for CRTM_Tutorial.

I would request you please help me to solve this issue at least give me some idea or document to compile crtm_tutorial with gcc or with intel.

Thanks & Regards
Raj

**Comment by StegmannJCSDA** [comment]
Hi @raj879423. 

For the `K-Matrix_test` executable, a simple makefile would look like this:
```make
all:
	gfortran -c -I/home/raj/codes/gcc/crtm_v2.2.3/include KMatrix_test.f90
	gfortran -L/home/raj/codes/gcc/crtm_v2.2.3/lib -lCRTM -o K.x KMatrix_test.o

clean:
	@rm *.o *.mod
```
assuming that you have installed the CRTM REL-2.2.3 version in `/home/raj/codes/gcc/crtm_v2.2.3/`.
If e.g. `crtm_atmosphere_define.mod` is located in the directory, but the compiler cannot find the references in this file, it is likely that there is some issue with your CRTM installation.

Another possible solution you could try is using lowercase `-lcrtm`, instead of `-lCRTM`.

Let me know if this works.

**Comment by raj879423** [comment]
Hi @StegmannJCSDA,

As per your suggestion i have tried the same way but it didn't work for me.
I would request you please guide me, how you have compiled this application CRTM_Tutorial from which version you have done with CRTM_REL.
It will be very helpful for me.

**Comment by StegmannJCSDA** [comment]
@raj879423 you already have all the necessary steps to compile the applications.
If it still does not compile successfully, you must have made a mistake in one of the steps or the CRTM did not compile successfully.

The only other suggestions I have are:
- you can try CRTM REL-2.3.0.
- you need to take care to compile the CRTM and the CRTM tutorial with the same compiler.

**Comment by StegmannJCSDA** [comment]
I noticed that you also removed the linker flag `-lCRTM` in the makefile and you don't have the `-L` option. 
As I have mentioned before, the correct linker step would look like this:
```make
gfortran -L/home/raj/codes/gcc/crtm_v2.2.3/lib -lCRTM -o K.x KMatrix_test.o
```

**Comment by StegmannJCSDA** [comment]
@raj879423 did that fix the problem?

**Comment by StegmannJCSDA** [comment]
Closing issue.
